
pipeline {
   agent {
       label 'master'
   } 

   parameters {
        string(name: 'featureFolder', defaultValue: '', description: 'Feature folders in git repo')
    }

   stages {
       stage('Checkout') {
           steps {
               git url: 'https://github.com/ramvalleru/JenkinsCIScan.git', branch: 'master'
           }
           
       }
       stage('Build') {
           steps {
               sh "cd ${Feature_folder}"
               sh "ls -lrt"
               // sh "mvn -Dmaven.test.failure.ignore=true clean package"
           }
       }
       /*
       stage('Publish') {
            steps {

            }
       }
       */
       
   }
}
